# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/_i_bitgen.xdc

# XDC: imports/constraints/vivado_target.xdc

# XDC: imports/constraints/_i_io.xdc

# Block Designs: bd/zusys/zusys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys || ORIG_REF_NAME==zusys} -quiet] -quiet

# IP: bd/zusys/ip/zusys_RGPIO_Master_CPLD_0/zusys_RGPIO_Master_CPLD_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_RGPIO_Master_CPLD_0 || ORIG_REF_NAME==zusys_RGPIO_Master_CPLD_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_RGPIO_Slave_CPLD_0/zusys_RGPIO_Slave_CPLD_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_RGPIO_Slave_CPLD_0 || ORIG_REF_NAME==zusys_RGPIO_Slave_CPLD_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_vio_rgpio_0/zusys_vio_rgpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_vio_rgpio_0 || ORIG_REF_NAME==zusys_vio_rgpio_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlconcat_2_0/zusys_xlconcat_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlconcat_2_0 || ORIG_REF_NAME==zusys_xlconcat_2_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlconcat_3_0/zusys_xlconcat_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlconcat_3_0 || ORIG_REF_NAME==zusys_xlconcat_3_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_0_0/zusys_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_0_0 || ORIG_REF_NAME==zusys_xlslice_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_1_0/zusys_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_1_0 || ORIG_REF_NAME==zusys_xlslice_1_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_2_0/zusys_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_2_0 || ORIG_REF_NAME==zusys_xlslice_2_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_3_0/zusys_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_3_0 || ORIG_REF_NAME==zusys_xlslice_3_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_4_0/zusys_xlslice_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_4_0 || ORIG_REF_NAME==zusys_xlslice_4_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_5_0/zusys_xlslice_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_5_0 || ORIG_REF_NAME==zusys_xlslice_5_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_6_0/zusys_xlslice_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_6_0 || ORIG_REF_NAME==zusys_xlslice_6_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_7_0/zusys_xlslice_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_7_0 || ORIG_REF_NAME==zusys_xlslice_7_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_8_0/zusys_xlslice_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_8_0 || ORIG_REF_NAME==zusys_xlslice_8_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_9_0/zusys_xlslice_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_9_0 || ORIG_REF_NAME==zusys_xlslice_9_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_10_0/zusys_xlslice_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_10_0 || ORIG_REF_NAME==zusys_xlslice_10_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_11_0/zusys_xlslice_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_11_0 || ORIG_REF_NAME==zusys_xlslice_11_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_12_0/zusys_xlslice_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_12_0 || ORIG_REF_NAME==zusys_xlslice_12_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_13_0/zusys_xlslice_13_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_13_0 || ORIG_REF_NAME==zusys_xlslice_13_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_14_0/zusys_xlslice_14_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_14_0 || ORIG_REF_NAME==zusys_xlslice_14_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_15_0/zusys_xlslice_15_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_15_0 || ORIG_REF_NAME==zusys_xlslice_15_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_16_0/zusys_xlslice_16_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_16_0 || ORIG_REF_NAME==zusys_xlslice_16_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_17_0/zusys_xlslice_17_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_17_0 || ORIG_REF_NAME==zusys_xlslice_17_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_18_0/zusys_xlslice_18_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_18_0 || ORIG_REF_NAME==zusys_xlslice_18_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlslice_19_0/zusys_xlslice_19_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlslice_19_0 || ORIG_REF_NAME==zusys_xlslice_19_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_SC0808BF_0_0/zusys_SC0808BF_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_SC0808BF_0_0 || ORIG_REF_NAME==zusys_SC0808BF_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_axis_live_audio_0_0/zusys_axis_live_audio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_axis_live_audio_0_0 || ORIG_REF_NAME==zusys_axis_live_audio_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_proc_sys_reset_0_0/zusys_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_proc_sys_reset_0_0 || ORIG_REF_NAME==zusys_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_vio_general_0/zusys_vio_general_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_vio_general_0 || ORIG_REF_NAME==zusys_vio_general_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_zynq_ultra_ps_e_0_0/zusys_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==zusys_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_capture_test1_0_0/zusys_capture_test1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_capture_test1_0_0 || ORIG_REF_NAME==zusys_capture_test1_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_touch_test_0_0/zusys_touch_test_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_touch_test_0_0 || ORIG_REF_NAME==zusys_touch_test_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_axi_smc_0/zusys_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_axi_smc_0 || ORIG_REF_NAME==zusys_axi_smc_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_rst_ps8_0_100M_0/zusys_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_rst_ps8_0_100M_0 || ORIG_REF_NAME==zusys_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_AXILite2_0_1/zusys_AXILite2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_AXILite2_0_1 || ORIG_REF_NAME==zusys_AXILite2_0_1} -quiet] -quiet

# XDC: /home/jackson/projects/Kestrel/AXItest/AXITest/AXITest.gen/sources_1/bd/zusys/zusys_ooc.xdc
