# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jackson/projects/test1/project_1/project_1.srcs/sources_1/bd/zusys/ip/zusys_proc_sys_reset_0_0/zusys_proc_sys_reset_0_0.xci
# IP: The module: 'zusys_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jackson/projects/test1/project_1/project_1.gen/sources_1/bd/zusys/ip/zusys_proc_sys_reset_0_0/zusys_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jackson/projects/test1/project_1/project_1.gen/sources_1/bd/zusys/ip/zusys_proc_sys_reset_0_0/zusys_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jackson/projects/test1/project_1/project_1.gen/sources_1/bd/zusys/ip/zusys_proc_sys_reset_0_0/zusys_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/jackson/projects/test1/project_1/project_1.srcs/sources_1/bd/zusys/ip/zusys_proc_sys_reset_0_0/zusys_proc_sys_reset_0_0.xci
# IP: The module: 'zusys_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jackson/projects/test1/project_1/project_1.gen/sources_1/bd/zusys/ip/zusys_proc_sys_reset_0_0/zusys_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jackson/projects/test1/project_1/project_1.gen/sources_1/bd/zusys/ip/zusys_proc_sys_reset_0_0/zusys_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/jackson/projects/test1/project_1/project_1.gen/sources_1/bd/zusys/ip/zusys_proc_sys_reset_0_0/zusys_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
