domain_path: /home/jackson/projects/Kestrel/AXItest/AXITest_WS/AXI4Test/zynqmp_fsbl/zynqmp_fsbl_bsp
app_src_dir: /tools/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
template: zynqmp_fsbl
lang: c
